### ISSUE TITLE
composer/installers conflicts

### ISSUE THREAD

**Issue by kitsunet** [neos/composer-plugin#11]
https://github.com/composer/installers/pull/330

We should add a `conflicts` entry to our composer.json and do what is suggested in the comment...

and MAYBE think about removing support for typo3-flow-* packages in this installer to remove the conflict as the other one only cares about typo3-flow packages (and works as long as those have PSR-0 autoload entries).

**Comment by kdambekalns** [comment]
A similar situation as in composer/installers#281 and composer/installers#300 - so we are as of now left with "is broken" or "impossible to installl". Other options?

We could update the installer to do what it needs to do to not be broken and deprecate it at the same time. Then hope it can be removed with a major release of composer/installers before we need to touch it again…

**Comment by RafaelKa** [comment]
What exactly could happen/be broken if `composer/installers` is installed for Flow(>3) instance?
And why we should and why NOT mark `composer/installers` as a conflicting lib?

Are there some packages/libreries available which require installers and which can be used jointly with Flow?
What happens by installation of package which is supported by some Installer from `composer/installers`? Goes it in the folder declared from other Installer or in the Libraries folder as from Flow suggested?

Some other side effects?
