### ISSUE TITLE
Require PHP 7.1

### ISSUE THREAD

**Issue by martinlipp** [neos/composer-plugin#15]
Since the new release 2.1.0 uses void return types in the Plugin class, the composer.json should require PHP 7.1+, the PHP version which introduced this feature. Otherwise this change breaks installations that still use Flow 4.x or older in combination with PHP 7.0 or older.
(Maybe not of the highest importance since it only concerns unsupported versions, but it would be an easy fix.)

**Comment by mrimann** [comment]
Oh, this breaking a fleet of installations on our side - would be cool if a v2.1.1 could be prepared with constraint on php >= 7.1.x (and 2.0.0 getting disabled on packagist.org).
This would save us a bunch of work hours (we're talking >50 Neos/Flow installations that are planned but not yet upgraded to 5.x LTS and Flow 6.x)

@kdambekalns is it possible to have a look into this and getting a releast shipped?

**Comment by kdambekalns** [comment]
A new 2.1.0 replaces the old 2.1.0 now. 😬

**Comment by mrimann** [comment]
Thanks @kdambekalns !
