### ISSUE TITLE
Error in Configuration validation since Flow 3.x

### ISSUE THREAD

**Issue by grebaldi** [neos/composer-plugin#6]
Hi there,

the configuration option `excludeClasses` has been deprecated in Flow, but is still used in this package. This causes `./flow configuration:validate --type Settings` to recognize this as an error:

```
Validating Settings configuration

1 errors were found:
 - Settings.TYPO3.Flow.object.excludeClasses -> This property is not allowed here, check the spelling if you think it belongs here.
```

**Comment by kdambekalns** [comment]
Yes, but the installer is used also for Flow versions were this setting still applies. And good, low-maintenance ideas to fix this are welcome. :)

**Comment by RafaelKa** [comment]
What about branching, taging and requiring this package with similar version as Flow and remove Settings.yaml for newer versions?

**Comment by bwaidelich** [comment]
We need to fix this.. It leads to a nasty error in _every_ Neos installation currently, that has already confused many integrators:
![image](https://cloud.githubusercontent.com/assets/307571/17368542/c875e3da-5994-11e6-9ce2-da51f7d06ba4.png)

👍  for using branches to solve this!

**Comment by aertmann** [comment]
yeah, also not much is happening in this package anyway so the overhead should be limited

**Comment by bwaidelich** [comment]
Ok, thx for the feedback. There's currently one branch `1.0` and I would now create one `2.0` w/o the obsolete setting. And then we'd probably have to change the composer manifests for the various distributions

**Comment by kitsunet** [comment]
actually I think the distributions don't even require it but Flow does, so that sohuld be easier!
Thanks for taking care.

**Comment by bwaidelich** [comment]
> actually I think the distributions don't even require it but Flow does

Ah, that would be even better!
But it seems at least the dev collection also requires 1.x currently:
https://github.com/neos/flow-development-collection/blob/master/composer.json#L23

**Comment by bwaidelich** [comment]
https://github.com/neos/composer-plugin/releases/tag/2.0.0

**Comment by bwaidelich** [comment]
aand https://github.com/neos/flow-development-collection/pull/414

**Comment by kitsunet** [comment]
👍

**Comment by tvt** [comment]
Hi,

So, if I download the 2.0.0 release it still contains the Configuration/Settings.yaml file. Am I missing something obvious?

**Comment by kitsunet** [comment]
Indeed something seems wrong there...

**Comment by kitsunet** [comment]
https://github.com/neos/composer-plugin/releases/tag/2.0.1 fixes that.

**Comment by tvt** [comment]
It seems that github is having issues. At least for me it shows the 2.0.1 release as being released on May 5.

But 2.0.1 works for me. Thanks!

**Comment by kitsunet** [comment]
I think that's because that is the date of the latest commit in the release.
