### ISSUE TITLE
"ExcludeClasses"-settings option no longer valid

### ISSUE THREAD

**Issue by dnepro** [neos/composer-plugin#8]
As of Flow version 3.0.0 the "TYPO3.Flow.object.excludeClasses"-setting is no longer valid and has been replaced by "TYPO3.Flow.object.includeClasses".

I would like to create a PR and fix this by completely remove the Settings.yaml (as it doesn't fulfill anything more than exactly this)

See Flow Changelog Entry
See Flow Issue #103

**Comment by kitsunet** [comment]
See 2.0 and master branch ;)

**Comment by kitsunet** [comment]
Version 2.0.1 can be used. Reopen if something is still missing.
