### ISSUE TITLE
composer.json's "support.issues" is no longer up-to-date

### ISSUE THREAD

**Issue by dnepro** [neos/composer-plugin#9]
As i see it, there is no "https://jira.neos.io" anymore and the issue tracker is now on github, would like to change this to "https://github.com/neos/composer-plugin/issues" in composer.json.

**Comment by kitsunet** [comment]
👍

**Comment by dnepro** [comment]
Against which branch should i make the PR, master?

**Comment by kitsunet** [comment]
Sorry missed your PM on Slack, I think 1.0 would be great as the fact that the info changed is also valid for older branches.

**Comment by dnepro** [comment]
I don't mind at least i now got the answer, thanks :)
